enum emotionEnums {
  VERY_BAD = 'VERY_BAD',
  BAD = 'BAD',
  SO_SO = 'SO_SO',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
}

enum accountEnums {
  FOOD = 'FOOD',
  CAFE = 'CAFE',
  ENTERTAIN = 'ENTERTAIN',
  LIVING = 'LIVING',
  ONLINE_SHOP = 'ONLINE_SHOP',
  FASSION = 'FASSION',
  BEAUTY = 'BEAUTY',
  TRAFFIC = 'TRAFFIC',
  CAR = 'CAR',
  DWELLING = 'DWELLING',
  HEALTH = 'HEALTH',
  FINANCE = 'FINANCE',
  CURTURE = 'CURTURE',
  TRABLE = 'TRABLE',
  EDUCATION = 'EDUCATION',
  CHILDREN = 'CHILDREN',
  PET = 'PET',
  PRESENT = 'PRESENT',
}

enum clsEnums {
  EXPENSE = 'EXPENSE',
  INCOME = 'INCOME',
  TRANSFER = 'TRANSFER',
}

enum OptionEnums {
  TODO_LIST = 'TODO_LIST',
  TODAY_QUESTION = 'TODAY_QUESTION',
  EMOTION_DIARY = 'EMOTION_DIARY',
  ACCOUNT_BOOK = 'ACCOUNT_BOOK',
}

export { emotionEnums, accountEnums, clsEnums, OptionEnums };
